### ISSUE TITLE
RubyGems

### ISSUE THREAD

**Issue by Zrp200** [szymon33/battleship#3]
I can help you put this on RubyGems. I've done it before

**Comment by szymon33** [comment]
I know that you can do that. I saw your profile. I know how to do that. It
is It is easy but the game is not ready yet. Please don't do that. If you
want to help then you can:
- take a look at CodeClimate and increase its rank
- write specs to have more coverage
- now it one board, one player plays agains the computer. Let's do it that
  player plays with computer (2 boards).
